name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: dxl2025*
          MYSQL_DATABASE: twitchanalytics
          MYSQL_ROOT_HOST: '%'
          TZ: UTC
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        command: [
          '--default-authentication-plugin=mysql_native_password',
          '--pid-file=/var/lib/mysql/mysql.pid'
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, curl, pdo, pdo_mysql

      - name: Cache Root Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-root-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-root-

      - name: Install root dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run code quality checks
        run: vendor/bin/grumphp run --verbose

      - name: Cache Lumen API Composer
        uses: actions/cache@v3
        with:
          path: lumen-api/vendor
          key: ${{ runner.os }}-composer-lumen-${{ hashFiles('lumen-api/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-lumen-

      - name: Install Lumen dependencies
        working-directory: ./lumen-api
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Environment
        working-directory: ./lumen-api
        run: |
          sed -i 's/DB_HOST=db/DB_HOST=127.0.0.1/g' .env.testing
          cp .env.testing .env

      - name: Run Tests
        working-directory: ./lumen-api
        run: |
          php artisan migrate:fresh --force
          vendor/bin/phpunit --testdox --configuration phpunit.xml
        env:
          APP_ENV: testing
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: twitchanalytics
          DB_USERNAME: root
          DB_PASSWORD: dxl2025*