name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: twitch_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, curl, pdo, pdo_mysql

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run code quality checks
        run: vendor/bin/grumphp run --verbose

      - name: Run Unit Tests
        run: vendor/bin/phpunit --testsuite Unit --testdox --configuration phpunit.xml

      - name: Prepare Environment
        run: |
          sed -i 's/DB_HOST=db/DB_HOST=127.0.0.1/g' .env.testing
          cp .env.testing .env

      - name: Run Integration Tests
        run: |
          php artisan migrate:fresh --force
          vendor/bin/phpunit --testsuite Feature --testdox --configuration phpunit.xml
        env:
          APP_ENV: testing
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: twitch_db
          DB_USERNAME: root
          DB_PASSWORD: root
